#!/bin/sh

if [ ! -f /conf/freenet.ini ]; then
    cp /defaults/freenet.ini /conf/
    sed -i "s#ALLOWEDHOSTS#$allowedhosts#" /conf/freenet.ini
    sed -i "s#DARKNETPORT#$darknetport#" /conf/freenet.ini
    sed -i "s#OPENNETPORT#$opennetport#" /conf/freenet.ini
fi

cd /fred

./run.sh console
